import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-screen w-screen min-h-screen min-w-screen max-w-screen max-h-screen overflow-x-hidden [&::-webkit-scrollbar]:hidden"
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-freesentation w-full h-full`}
      >
        {children}
        <Analytics />
      </body>
    </html>
  );
}
